### ISSUE TITLE
Sprint 3: Implement a cache strategy for iOS - Juanda

### ISSUE THREAD

**Issue by jsalguero1** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#104]

**Comment by jsalguero1** [comment]
I already did a cache strategy for our transactions, please @Danielclavijo55 review my branch for this functionality so i can do a PR for our project

**Comment by Danielclavijo55** [comment]
Brilliant! I see that you already explained it in detail in the project wiki, great job.
