### ISSUE TITLE
Sprint 3: Finish Authentication Feature Integration in iOS - Daniel

### ISSUE THREAD

**Issue by Danielclavijo55** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#106]

**Comment by Danielclavijo55** [comment]
The main now has the authentication function completed. You can close the issue. @fai-aher

**Comment by fai-aher** [comment]
The Authentication feature was improved in comparison to the Sprint 2 deliverable. I checked it and it works smootly. I procceed with accepting this issue and updating it as ** _Completed._**
