### ISSUE TITLE
Sprint 3: Implement BQ 18 - Jose

### ISSUE THREAD

**Issue by J0FR** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#109]

**Comment by J0FR** [comment]
Hello @NCKDayz,

I have completed the task, and the implementation is available for review in the following pull request: [Pull Request #41](https://github.com/ISIS3510-MOBILE-T34/SpendiQ_Android/pull/41).

The pull request is currently pending and has not yet been merged into the main branch of the Android application. Please verify the functionality to ensure it meets the acceptance criteria. If everything is satisfactory, kindly proceed with integrating it into the main branch.

Thank you!

**Comment by NCKDayz** [comment]
@J0FR
Everything looks good. Already accepted your pull request!
