### ISSUE TITLE
Sprint 3: Implement Multi-threading Strategy for Android - Jose

### ISSUE THREAD

**Issue by J0FR** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#110]

**Comment by J0FR** [comment]
Hello @NCKDayz,

I have completed the task, and the implementation has been merged into the main branch of the Android application. You can review the work in the following pull request: [Pull Request #33](https://github.com/ISIS3510-MOBILE-T34/SpendiQ_Android/pull/33).

Please verify the functionality to ensure it meets the acceptance criteria. If everything is satisfactory, feel free to close this issue. Let me know if any adjustments are needed.

Thank you!

**Comment by NCKDayz** [comment]
@J0FR 
Everything looks good. Already accepted your pull request!
