### ISSUE TITLE
Sprint 3: Review Teammates' Work to Prepare for Viva Voce - Daniel

### ISSUE THREAD

**Issue by Danielclavijo55** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#112]

**Comment by Danielclavijo55** [comment]
We are now ready to support Viva Voce, we will be there! @fai-aher

**Comment by fai-aher** [comment]
Perfect. Let's review your work as a team to prepare for the group viva voce. I proceed to complete this issue successfully.
