### ISSUE TITLE
Sprint 3: Formulate a new BQ in the Wiki and Implement it - Daniel

### ISSUE THREAD

**Issue by Danielclavijo55** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#113]

**Comment by Danielclavijo55** [comment]
You can now find the BQ in the Sprint 3 wiki. You can now close the issue. @fai-aher

**Comment by fai-aher** [comment]
I just checked your new BQ description in the wiki and then the implementation. Both are correct and proper as the BQ type you chose. I proceed to complete this issue successfully.
