### ISSUE TITLE
Sprint 3: Define and Document New Business Questions (d, e, f) - Daniel

### ISSUE THREAD

**Issue by Danielclavijo55** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#114]

**Comment by Danielclavijo55** [comment]
The wiki is now complete for the delivery of sprint 3. @fai-aher

**Comment by fai-aher** [comment]
Great. I just checked the description of the new BQ you prepared for the app. They also work fine when running the app from the Xcode emulator. Great job. I proceed to complete this issue successfully.
