### ISSUE TITLE
Sprint 3: Implement Multi-threading Strategy for iOS - Daniel

### ISSUE THREAD

**Issue by Danielclavijo55** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#115]

**Comment by Danielclavijo55** [comment]
The respective PR has already been carried out in the iOS application to comply with the multi-threading strategy. @fai-aher

**Comment by fai-aher** [comment]
Nice job with the implementation of Multi-threading, which is realted to a pull request that I just reviewed from you and accepeted. Nice job. I proceed to complete this issue successfully.
