### ISSUE TITLE
Sprint 3: Define and Add to Wiki Eventual Conectivity Strategy  - Nick

### ISSUE THREAD

**Issue by NCKDayz** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#116]

**Comment by NCKDayz** [comment]
@Juanchix 
Finished this task.

If you see any bugs or issues let me know!

**Comment by Juanchix** [comment]
I make a little UI modifications to make it more enjoyable. So far, I have not seen any bugs. If there are or we find them later, we will fix them.
