### ISSUE TITLE
Sprint 3: Define and Add to Wiki Local Storage Strategy - Nick

### ISSUE THREAD

**Issue by NCKDayz** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#118]

**Comment by NCKDayz** [comment]
@Juanchix 
Finished this task.

If you see any bugs or issues let me know!

**Comment by Juanchix** [comment]
I would like to stress the importance of handling encryption, since we are handling highly sensitive information, so we must be careful when storing and processing this data.
