### ISSUE TITLE
Sprint 1: Provide Quality Scenarios for the solution (Wiki) - Team

### ISSUE THREAD

**Issue by Juanchix** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#12]

**Comment by fai-aher** [comment]
It was reviewed and integrated to the Wiki for the Sprint 1 delivery.

**Comment by fai-aher** [comment]
It was reviewed and integrated to the Wiki for the Sprint 1 delivery.

**Comment by fai-aher** [comment]
It was reviewed and integrated to the Wiki for the Sprint 1 delivery.
