### ISSUE TITLE
Sprint 3: Define BQ 18 - Jose

### ISSUE THREAD

**Issue by J0FR** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#120]

**Comment by J0FR** [comment]
Hello @NCKDayz,

I have completed the task as outlined in the issue. You can review the documentation at the following link: [BQ18 - Made by Jose David Florez Ruiz](https://github.com/ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ/wiki/BQ18---Made-by-Jose-David-Florez-Ruiz).

Please review the work, and if everything is satisfactory, feel free to close this issue. Let me know if any adjustments are needed.

Thank you!

**Comment by NCKDayz** [comment]
@J0FR
Everything looks good. Already accepted your pull request!
