### ISSUE TITLE
Sprint 3: Define Multi-threading Strategy for Android - Jose

### ISSUE THREAD

**Issue by J0FR** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#121]

**Comment by J0FR** [comment]
Hello @NCKDayz,

I have completed the task as outlined in this issue. You can review the documentation at the following link: [Multi-threading - Concurrency Strategy for Both Mobile Applications](https://github.com/ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ/wiki/Multi-threading---Concurrency-Strategy-for-Both-Mobile-Applications).

Additionally, please review and accept the pull request containing the accompanying diagram: [Pull Request #122](https://github.com/ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ/pull/122).

If everything looks good, feel free to close this issue. Let me know if any adjustments are needed.

Thank you!

**Comment by NCKDayz** [comment]
@J0FR
Everything looks good. Already accepted your pull request!
