### ISSUE TITLE
Sprint 4: Define value proposition - Jose David Florez Ruiz

### ISSUE THREAD

**Issue by J0FR** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#128]

**Comment by J0FR** [comment]
Hi @NCKDayz, the issue "Sprint 4: Define value proposition" is ready to close. Let me know if there are any changes required.

**Comment by NCKDayz** [comment]
Closing this issue as the implementation is complete and everything has been verified. If any problems arise, feel free to reopen it. Thanks!

Closes #128
