### ISSUE TITLE
Sprint 4: Design, implement and justify micro-optimization strategy - Jose David Florez Ruiz

### ISSUE THREAD

**Issue by J0FR** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#129]

**Comment by J0FR** [comment]
Hi @NCKDayz, the issue "Sprint 4: Design, implement and justify micro-optimization strategy" is ready to close. Let me know if anything needs to be changed.

**Comment by NCKDayz** [comment]
Closing this issue as the implementation is complete and everything has been verified. If any problems arise, feel free to reopen it. Thanks!

Closes  #129

**Comment by NCKDayz** [comment]
Closing this issue as the implementation is complete and everything has been verified. If any problems arise, feel free to reopen it. Thanks!

Closes  #129
