### ISSUE TITLE
Sprint 4: Implement new view - Jose David Florez Ruiz

### ISSUE THREAD

**Issue by J0FR** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#132]

**Comment by J0FR** [comment]
Hi @NCKDayz, the issue "Sprint 4: Implement new view" is ready to close. Let me know if any changes are needed.

**Comment by NCKDayz** [comment]
Closing this issue as the implementation is complete and everything has been verified. If any problems arise, feel free to reopen it. Thanks!

Closes #132
