### ISSUE TITLE
Sprint 4: Implement new BQ - Jose David Florez Ruiz

### ISSUE THREAD

**Issue by J0FR** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#133]

**Comment by J0FR** [comment]
Hi @NCKDayz, the issue "Sprint 4: Implement new BQ" is ready to close. Let me know if any changes are required.

**Comment by NCKDayz** [comment]
Closing this issue as the implementation is complete and everything has been verified. If any problems arise, feel free to reopen it. Thanks!

Closes #133
