### ISSUE TITLE
Sprint 1 | MS4 (Fix): Context Canvas "Upload the real one 🫠"

### ISSUE THREAD

**Issue by J0FR** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#21]
Context Canvas:

            Points: 1

            Feedback: Problem and solution statement was not aligned with the problem you were talking about in the Personas, PAS, BQs, etc. Personas section has no relation with finance app. You app section does not follow the same topic as the  Personas, PAS, BQs, etc. Backend services are ok because it a technical stuff. Constraints for backend services are good but just those.

**Comment by fai-aher** [comment]
The real context canvas was updated!  I just checked it and it has no problems.
