### ISSUE TITLE
Sprint 2: Define Color pallete - All Team

### ISSUE THREAD

**Issue by jsalguero1** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#38]

**Comment by fai-aher** [comment]
We met as a team in a videocall, reviewed the selected color pallete and we all agreed on using it from now on. Therefore, I declare this issue as closed with a successful resolution.
![Image](https://github.com/user-attachments/assets/90f7b2b1-6eda-4cbe-82db-c51aab63897a)
