### ISSUE TITLE
Sprint 2: Implement BQ_3 in Firebase

### ISSUE THREAD

**Issue by jsalguero1** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#39]
Implement Bussines Question #3 in the firebase

**Comment by jsalguero1** [comment]
every transaction thta is created has a dateTime so for answering this BQ we can analyze the hours of the transactions in a given range of dates to determine the answer to the following question:

_At which time of the day do users most frequently log into their daily cash expenses?_

**Comment by jsalguero1** [comment]
I need review from @Danielclavijo55 in order to mark this as done

**Comment by Danielclavijo55** [comment]
Okay, issue closed when reviewing the team's firebase, the BQs are fulfilled. Closes #39
