### ISSUE TITLE
Sprint 2: implement BQ_4 in Firebase

### ISSUE THREAD

**Issue by jsalguero1** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#40]
Implement Bussiness Question #4 in Firebase

**Comment by jsalguero1** [comment]
This BQ is not yet implemented but we are aiming to! the purpose is to give users a personalized feedback whenever they are having better or worse financial habits. this BQ is trying to respond to the question:

 _How many days has it been since the app gave the user any financial guidance?_

**Comment by Danielclavijo55** [comment]
Okay, issue closed when reviewing the team's firebase, the BQs are fulfilled. Closes #40
