### ISSUE TITLE
Sprint 2: Smart feature user story

### ISSUE THREAD

**Issue by jsalguero1** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#41]
Do the user story for the smart feature of the app

**Comment by jsalguero1** [comment]
I'll put here the User Story and its acceptance criteria, after @Danielclavijo55 review my work and accept it i will put it in the wiki 

**User Story: Automatic Transaction Registration from SMS**

- (Role) - As a user of SpendiQ,
- (Action) - I want the app to read my SMS messages and automatically detect keywords related to financial transactions,
- (Value) - so that transactions are recorded automatically in my account without needing to do it manually.

**Acceptance Criteria:**

- The app must be able to access and read the user’s SMS messages (with prior authorization).
- The system should correctly identify keywords such as "deposit," "payment," "withdrawal," "transfer". 
- Transactions should be automatically categorized by type (income or expense) and recorded in the appropriate account within the app.
- The app must notify the user when a transaction is registered from an SMS.
- The user should be able to verify and correct a registered transaction if necessary.

**Comment by Danielclavijo55** [comment]
Hey Juan David, I see that the structure of the story is fulfilled and is clear and specific enough, great work. Issue Approved
