### ISSUE TITLE
Sprint 2: Smart feature functional scenario

### ISSUE THREAD

**Issue by jsalguero1** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#43]
Do the functional scenario for the smart feature of the app

**Comment by jsalguero1** [comment]
I'll leave the funcitonal scenario here until @Danielclavijo55 reviews and approve it, then i'll put it in the team's wiki

> Given` that the user has granted the app permission to access their SMS messages, and has received an SMS from their bank notifying them of a movements, when the system detects the SMS and identifies a keyword related to a transaction and the transaction amount, the app should automatically classify the transaction, update the account within the app, and notify the user that the transaction has been successfully recorded.

**Comment by Danielclavijo55** [comment]
Functional Scenario well defined, meets the defined structure and purpose of the feature. Close #43
