### ISSUE TITLE
Sprint 2: Design the Architectural Style for SpendiQ Mobile App - Alonso

### ISSUE THREAD

**Issue by fai-aher** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#44]

**Comment by fai-aher** [comment]
I defined 2 architectural styles, one being multi-layered and the other being the Pipes and Filter to process data from the backend. Please check that everything is correct and help me approve this issue @jsalguero1

**Comment by jsalguero1** [comment]
Everything correct in the Styles. Issue Approved
