### ISSUE TITLE
Sprint 2: Design the Architectural Patterns for SpendiQ Mobile App - Alonso

### ISSUE THREAD

**Issue by fai-aher** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#45]

**Comment by fai-aher** [comment]
The architectural patterns were designed, diagramed and explained in the wiki section. Please review them and help me approve this issue @jsalguero1

**Comment by jsalguero1** [comment]
I saw the work and it is a quality job. Great work at definig the architecturan patterns Alonso. Issue Approved
