### ISSUE TITLE
Sprint 2: Define the Design Patterns for SpendiQ Mobile App - Alonso

### ISSUE THREAD

**Issue by fai-aher** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#46]

**Comment by fai-aher** [comment]
The Design Patterns were described and added to the wiki of the project. Please help me review them and approve them @jsalguero1

**Comment by jsalguero1** [comment]
I read them and they look right. They are coherent and the ratioanle is there. Issue Approved
