### ISSUE TITLE
Sprint 2: Prepare and Start the Analytics Engine with Google Firebase - Alonso

### ISSUE THREAD

**Issue by fai-aher** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#48]

**Comment by fai-aher** [comment]
The Firebase's Firestore instance was initiated and the collections created according to the Models we need in the MVVM model. Please review them and approve my work @jsalguero1

**Comment by jsalguero1** [comment]
The firebase is working right now, i have used it so the work is done. Issue Approved
