### ISSUE TITLE
Sprint 2: Implement the BQ11 inside the Analytics Engine - Alonso

### ISSUE THREAD

**Issue by fai-aher** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#49]

**Comment by fai-aher** [comment]
The BQ 11: What percentage of our app users show spending patterns indicative of being able to pay for premium features? Was solved in the Firestore instance by creating collections with attributes that allow to answer this question and then show it to the user in the app. Please review them and complete my issue@jsalguero1 u

**Comment by jsalguero1** [comment]
Great work, Firebase is already functional at this point. Issue Approved
