### ISSUE TITLE
Sprint 2: Implement the BQ12 inside the Analytics Engine - Alonso

### ISSUE THREAD

**Issue by fai-aher** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#50]

**Comment by fai-aher** [comment]
The BQ 12: Which are the top 10 users who have made the most purchases in a specific area of the city in the last 3 months? Was solved thanks to the introduction of the user_location collection inside the Firestore instance in the backend. Please help me complete this issue @jsalguero1

**Comment by jsalguero1** [comment]
Great Job Alonso! Issue Approved
