### ISSUE TITLE
Sprint 6 and MS7: Create 2 Mock-ups for the CAS Functionality in the Team Figma - Alonso

### ISSUE THREAD

**Issue by fai-aher** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#54]

**Comment by fai-aher** [comment]
![Image](https://github.com/user-attachments/assets/b27904b8-3b51-4d13-b01e-67de6a323f9c)
The Mock Ups have been created. Waiting for my Reviwer's Feedback @jsalguero1

**Comment by jsalguero1** [comment]
Hey Alonso, I think they are fine, they are clear and fulfil your responsability for this task! Great job
