### ISSUE TITLE
Sprint 2: Implement the CAS Functionality in the iOS App (Swift Team) - Alonso

### ISSUE THREAD

**Issue by fai-aher** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#55]

**Comment by fai-aher** [comment]
The CAS functionality was implement in the iOS app with the corresponding Models, Viewmodels and the views prepared, which correspond to the mockups made with FIGMA. Please test them and help me approve them @jsalguero1

**Comment by jsalguero1** [comment]
Well done Aonso, your branch is already in the Main so it's working. Issue Approved
