### ISSUE TITLE
Design Figma: Work in the Landing Page of the App - Team

### ISSUE THREAD

**Issue by fai-aher** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#6]

**Comment by jsalguero1** [comment]
This task is going to be under my responsability for now

**Comment by jsalguero1** [comment]
![Image](https://github.com/user-attachments/assets/68485571-0add-4f7c-92ee-e2946db0cd1f)
Here are my mockups for the landing page! Please @Danielclavijo55 review them and tell me if there is something to be fixed, thanks.

**Comment by Danielclavijo55** [comment]
Great Main page, the usage of the color palette is appropiate and the organization of the page is well structured. Closes #6
