### ISSUE TITLE
Sprint 2 and MS7: Create 2 Mock-ups for the Authentication Functionality in the Team Figma - Daniel

### ISSUE THREAD

**Issue by Danielclavijo55** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#65]

**Comment by Danielclavijo55** [comment]
After Alonso @fai-aher reviews the MockUps they will be uploaded to the project's wiki in the MS7 section.

![Image](https://github.com/user-attachments/assets/c594978c-505f-4b04-933f-002fb716ad82)

**Comment by fai-aher** [comment]
Hey Daniel! I hope you are doing good. I reviewed your mock ups carefully and they all seem fine because they follow the design decisions made by the team. Therefore, I accept the resolution of this issue as successful.
