### ISSUE TITLE
Sprint 2: Define the Authentication Functionality through a Functional Scenario - Daniel

### ISSUE THREAD

**Issue by Danielclavijo55** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#66]

**Comment by Danielclavijo55** [comment]
@fai-aher 
Functional Scenario (Auth Feature):
Scenario: New Student User Registration and Login given that Jeison, an 18-year-old student in Colombia, has downloaded the SpendiQ app on his latest model iPhone When he opens the app for the first time, then he is presented with options to "Sign Up" or "Log In”, when he taps on "Sign Up”, then he is prompted to enter his university email and create a password. When he completes the registration form and submits it, then the app verifies his email and creates his account with customized budget categories for students and he is automatically logged in, shown a brief introduction to the saving and expense tracking features. When he closes the app and reopens it later, then he is prompted to log in with his email and password. When he enters his credentials correctly, then he successfully logs in and is taken to his personalized dashboard showing a summary of his academic and social expenses.

**Comment by fai-aher** [comment]
Very nice job with the functional scenario, it follows the structure recommended by the professor Mario. I approve it and close this issue.
