### ISSUE TITLE
Sprint 2: Define the Authentication Functionality through a User Story - Daniel

### ISSUE THREAD

**Issue by Danielclavijo55** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#68]

**Comment by Danielclavijo55** [comment]
@fai-aher 
User Story (Auth Feature) :As Jeison, an 18-year-old university student, I want to create a SpendiQ account and access it securely and quickly, So that I can control my academic and social expenses, save for my post-graduation plans, all while keeping my financial information protected.

**Comment by fai-aher** [comment]
I reviewed the User Story and it follows the structure: I reviewed it and the implementation was as expected, good job. Therefore, I approve this issue and close it.. Therefore, I approve this issue and close it.
