### ISSUE TITLE
Sprint 2: Define the external service usage through a Functional Scenario - Jose

### ISSUE THREAD

**Issue by J0FR** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#71]

**Comment by J0FR** [comment]
Hey @Danielclavijo55, I’ve completed the work on this issue. Can you review it when you have a moment? Let me know if any adjustments are needed. Thanks!


**Content:** 
Functionality Scenarios

Goal: Implement two-step authentication for increased security during the login process.

Scenario 1:

Context: A user is logging into SpendIQ and has enabled two-step authentication.
System Behavior: When the user enters their email and password, the system should send a verification code via SMS or WhatsApp. Once the user enters the correct code, the system grants access to the app. If the code is incorrect, the system prompts the user to re-enter the code.
Scenario 2:

Context: A user has not enabled two-step authentication.
System Behavior: When the user logs into SpendIQ using only their email and password, the system will allow access without requiring a verification code.
Scenario 3:

Context: A user chooses to enable or disable two-step authentication from the app settings.
System Behavior: The system should prompt the user to verify their identity (e.g., by entering a password or using biometrics) to confirm the change. Once verified, two-step authentication will either be enabled or disabled.
Scenario 4:

Context: A user does not receive the verification code.
System Behavior: The system will allow the user to request a resend of the verification code via SMS or WhatsApp.

**Comment by NCKDayz** [comment]
Approved. Good Job for making 3 scenarios!
