### ISSUE TITLE
Sprint 2: Define the external service usage through a User Story - Jose

### ISSUE THREAD

**Issue by J0FR** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#72]

**Comment by J0FR** [comment]
Hey @Danielclavijo55, I've completed this user story. Could you review it when you get a chance and let me know if any changes are required? Thanks!

**Content:**

User Story

As a user of SpendIQ, I want to enable two-step authentication so that I can receive a verification code via SMS or WhatsApp to ensure secure access to my financial data.

**Comment by NCKDayz** [comment]
Approved.
