### ISSUE TITLE
Sprint 2: Define the external service usage through a Quality Scenario - Jose

### ISSUE THREAD

**Issue by J0FR** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#73]

**Comment by J0FR** [comment]
Hey @Danielclavijo55, I've finished defining this quality scenario. Please take a look when you have a moment and let me know if any changes are needed. Thanks!

**Content:**
## Quality Scenarios

### Scenario #1: Two-step Authentication SMS Delivery Delay

| **Aspect**                                      | **Description**                                                                                                                                                                |
|-------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Quality attributes involved**                 | Performance, Resilience, Security                                                                                                                                               |
| **App status and context**                      | The user is logging into the app and waiting for the SMS verification code.                                                                                                     |
| **Changes in the context**                      | The SMS with the verification code takes longer than expected to arrive due to network issues.                                                                                   |
| **System reaction**                             | The system should detect the delay and provide an option to resend the verification code or choose an alternative method (e.g., WhatsApp) without affecting the user's security or access. |

### Scenario #2: Incorrect Verification Code Entered

| **Aspect**                                      | **Description**                                                                                                                                                                |
|-------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Quality attributes involved**                 | Security, Usability                                                                                                                                                            |
| **App status and context**                      | The user has received an SMS with the verification code and enters it in the app.                                                                                              |
| **Changes in the context**                      | The user enters an incorrect verification code.                                                                                                                                 |
| **System reaction**                             | The system should immediately inform the user of the incorrect code and prompt them to re-enter or resend the code after a set number of failed attempts, without compromising usability. |

### Scenario #3: User Changes Phone Number Before Login

| **Aspect**                                      | **Description**                                                                                                                                                                |
|-------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Quality attributes involved**                 | Resilience, Security                                                                                                                                                           |
| **App status and context**                      | The user has changed their phone number but is attempting to log in using two-step authentication that is still linked to their old number.                                      |
| **Changes in the context**                      | The user tries to log in, but the SMS is sent to their old number, which they no longer have access to.                                                                          |
| **System reaction**                             | The system should allow the user to update their phone number via an alternative verification process (such as email verification), ensuring secure account access.               |

---

### Scenario #4: Account Lockout After Multiple Failed Authentication Attempts

| **Aspect**                                      | **Description**                                                                                                                                                                |
|-------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Quality attributes involved**                 | Security, Usability, Resilience                                                                                                                                                |
| **App status and context**                      | The user has failed multiple times to enter the correct verification code during two-step authentication.                                                                       |
| **Changes in the context**                      | After repeated failed attempts, the user is locked out of the account for security reasons.                                                                                      |
| **System reaction**                             | The system should lock the account after a set number of failed attempts and prompt the user to use alternative recovery methods (e.g., email verification or support contact) while ensuring the account remains secure. |

### Scenario #5: Processing Multiple SMS Messages from Banks and Financial Services

| **Aspect**| **Description**                                                          |
|-------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Quality attributes involved**| Performance, accuracy, resilience, scalability                                                                                                                                  |
| **App status and context**| The app is running in the background, and the user receives multiple SMS messages from different banks and financial services, all containing transaction details.                |
| **Changes in the context**                      | The user receives several messages within a short period of time. The app needs to detect these messages, extract relevant transaction information (keywords, amounts, etc.), and update the transaction history of the appropriate accounts. |
| **System reaction**                             | The app should process each message within 2 seconds, accurately identifies transaction-related keywords, and updates the appropriate account. The system maintains an error rate of less than 1% in detecting keywords, while ensuring the app's overall performance remains unaffected by the influx of messages. If an error occurs, it queues the message for reprocessing without interrupting the user experience.               |

**Comment by NCKDayz** [comment]
Approved.
