### ISSUE TITLE
Sprint 2: Analytics Pipeline Description - Jose

### ISSUE THREAD

**Issue by J0FR** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#74]

**Comment by J0FR** [comment]
Hey @Danielclavijo55, I’ve wrapped up this task. Please review it when you have some time and let me know if any changes are needed. Thanks!


**Content:**

This pipeline collects, preprocesses, models, stores, and visualizes data for comprehensive analysis. Below is a step-by-step breakdown of each stage:

### 2.1 Data Source Collection
We collect data from:
- **Bank Notifications**: Transaction details are extracted from user banking activities.
- **User Registrations**: Information gathered during user sign-ups for further analysis.

### 2.2 Data Pre-Processing
Data is preprocessed within the app using **Kotlin**. Basic operations include:
- Extracting the transaction amount.
- Identifying the company associated with each transaction.

![Data Pre-Processing](path_to_image)

### 2.3 Data Modeling
We structure the data for modeling by organizing key features like:
- Transaction amounts.
- Company details.
These features are categorized for efficient analysis and predictive modeling.

### 2.4 Storage
We store the processed data using:
- **Google Cloud Firestore**: A scalable and flexible database solution.
- **Firebase Authentication**: Securely manages user credentials and access control.

### 2.5 Visualization
We use **Google Analytics** for creating dashboards and reports that provide insights into:
- User behavior.
- Transaction patterns.
- Key performance metrics.

This helps in monitoring and making data-driven decisions.

**Comment by NCKDayz** [comment]
Approved. Looks good!
