### ISSUE TITLE
Sprint 2: Define the external service usage through a mockup - Jose

### ISSUE THREAD

**Issue by J0FR** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#76]

**Comment by J0FR** [comment]
Hey @Danielclavijo55 , I’m done with this task. Could you please take a look and verify that everything is correct when you have time? Appreciate it!

![Image](https://github.com/user-attachments/assets/81aa6eb0-3e69-4829-8275-1e90a987fd60)

Let me know if you have any comments!

**Comment by NCKDayz** [comment]
Approved. Nice mockup. It sells the feature.
