### ISSUE TITLE
Sprint 3: Describe 6 Eventual Connection Strategies for Android and iOS Apps - Alonso

### ISSUE THREAD

**Issue by fai-aher** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#95]

**Comment by fai-aher** [comment]
I just made a document with all the Eventual Connectivity Scenarios for 6 functionalities. At the end, I had to include a new feature because one of the previous 6 could no handle this kind of scenario. Please check my work and help me approve it @jsalguero1

**Comment by jsalguero1** [comment]
Alonso I saw your document and I think Is correct. great job.  Issue Closed
