### ISSUE TITLE
Sprint 3: Justify the Decision of Choosing and Implementing the 6 Eventual Connection Strategies - Alonso

### ISSUE THREAD

**Issue by fai-aher** [ISIS3510-MOBILE-T34/T34-Wiki-SpendiQ#96]

**Comment by fai-aher** [comment]
I included justification for making each Eventual Connectivity Scenario in the Wiki and in the PDF I prepared for the Sprint 3 Launching. It can be accessed in the Wiki --> Sprint 3 Deliverable Section. Please check the justifications and help me approve them @jsalguero1

**Comment by jsalguero1** [comment]
Alonso i just reviewed your job and its well done, every scenario is correctly defined and complte. Issue Closed
